### ISSUE TITLE
Omg, the logo is buggy, fix it.

### ISSUE THREAD

**Issue by zTonyzinz** [elizeujrdev/pizzaria#2]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, turpis sit amet consectetur consectetur, neque massa vestibulum dolor, ac hendrerit risus enim et odio. Donec suscipit et erat et eleifend. Cras eu posuere turpis. Ut sed quam pulvinar, vulputate purus nec, vulputate ex. Etiam in fermentum mauris. Nullam tincidunt porta arcu. Aliquam cursus urna vel commodo eleifend.

Cras a orci at mauris gravida scelerisque. Sed feugiat, turpis viverra laoreet vehicula, sem urna euismod magna, eget ultrices velit nisi eu ipsum. Nunc maximus sem neque, non auctor dui egestas vel. Suspendisse cursus sagittis massa, a venenatis ante fringilla ut. Fusce elementum sit amet orci non varius. Aenean rhoncus justo tortor. Suspendisse feugiat elit massa, id tempus ante mattis et. Nunc sapien ante, commodo et orci sit amet, suscipit cursus purus. Cras ac nisi pharetra quam dictum viverra eu vel urna.

Quisque vulputate et sem ac efficitur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla luctus ullamcorper ligula id cursus. Nam velit justo, dignissim ac augue vitae, blandit dignissim nibh. Sed sit amet ultricies ante. Proin eget porta tortor. Curabitur a eros sapien. Nulla imperdiet nisl facilisis euismod sodales. Proin lobortis, risus posuere eleifend lacinia, leo enim venenatis sapien, sit amet tincidunt est lectus tempor sem. Vestibulum elementum, purus id pellentesque tristique, odio purus rhoncus lacus, non cursus dolor libero a risus. Proin non libero enim. Morbi ultricies tempor ligula. Ut sem purus, efficitur pharetra malesuada nec, molestie nec justo.

**Comment by danielspinard** [comment]
Bro, but i fixed this with the message: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, turpis sit amet consectetur consectetur, neque massa vestibulum dolor, ac hendrerit risus enim et odio. Donec suscipit et erat et eleifend. Cras eu posuere turpis. Ut sed quam pulvinar, vulputate purus nec, vulputate ex. Etiam in fermentum mauris. Nullam tincidunt porta arcu. Aliquam cursus urna vel commodo eleifend.

Cras a orci at mauris gravida scelerisque. Sed feugiat, turpis viverra laoreet vehicula, sem urna euismod magna, eget ultrices velit nisi eu ipsum. Nunc maximus sem neque, non auctor dui egestas vel. Suspendisse cursus sagittis massa, a venenatis ante fringilla ut. Fusce elementum sit amet orci non varius. Aenean rhoncus justo tortor. Suspendisse feugiat elit massa, id tempus ante mattis et. Nunc sapien ante, commodo et orci sit amet, suscipit cursus purus. Cras ac nisi pharetra quam dictum viverra eu vel urna.

Quisque vulputate et sem ac efficitur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla luctus ullamcorper ligula id cursus. Nam velit justo, dignissim ac augue vitae, blandit dignissim nibh. Sed sit amet ultricies ante. Proin eget porta tortor. Curabitur a eros sapien. Nulla imperdiet nisl facilisis euismod sodales. Proin lobortis, risus posuere eleifend lacinia, leo enim venenatis sapien, sit amet tincidunt est lectus tempor sem. Vestibulum elementum, purus id pellentesque tristique, odio purus rhoncus lacus, non cursus dolor libero a risus. Proin non libero enim. Morbi ultricies tempor ligula. Ut sem purus, efficitur pharetra malesuada nec, molestie nec justo.

**Comment by zTonyzinz** [comment]
I see you fixed, but not exists readme. Fixed it!

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse viverra quam nibh, at condimentum velit commodo fermentum. Duis suscipit nisl at orci eleifend pharetra. Vivamus sodales rhoncus ornare. Ut vel lorem nec urna tristique iaculis. Proin viverra dui id lacinia accumsan. Etiam dignissim id turpis sit amet tempus. Vivamus id mauris ante. Aliquam viverra purus vehicula, iaculis quam eu, fermentum urna. Morbi at justo mi. Duis ipsum augue, scelerisque vel est in, facilisis vestibulum augue. Integer eleifend lorem non erat facilisis hendrerit. Nulla facilisi. Praesent luctus tempor lorem, ut mollis neque tincidunt viverra. Morbi et ex sit amet nisi congue pellentesque. Nunc gravida sagittis sollicitudin. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Nam elementum pellentesque ipsum eget sodales. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In malesuada commodo sem sed congue. Morbi fringilla, ligula nec tincidunt vestibulum, mi libero gravida tortor, a laoreet metus nunc in magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam vel lorem erat. Suspendisse et volutpat mi. Fusce gravida tellus erat, eget feugiat lacus bibendum a. Duis rutrum fermentum sollicitudin. Pellentesque hendrerit tempus sapien ac molestie. Aliquam accumsan hendrerit turpis vitae auctor. Donec quam ante, posuere id fringilla a, tempor nec lacus. Etiam at ullamcorper diam, vel laoreet risus. Proin venenatis tortor ante, ut cursus nisi suscipit et. Duis at mi aliquam, porttitor sapien ac, aliquet mauris. Quisque sed mauris interdum, placerat lorem ut, consectetur mi.

**Comment by danielspinard** [comment]
READ.me is not important why lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, turpis sit amet consectetur consectetur, neque massa vestibulum dolor, ac hendrerit risus enim et odio. Donec suscipit et erat et eleifend. Cras eu posuere turpis. Ut sed quam pulvinar, vulputate purus nec, vulputate ex. Etiam in fermentum mauris. Nullam tincidunt porta arcu. Aliquam cursus urna vel commodo eleifend.

Cras a orci at mauris gravida scelerisque. Sed feugiat, turpis viverra laoreet vehicula, sem urna euismod magna, eget ultrices velit nisi eu ipsum. Nunc maximus sem neque, non auctor dui egestas vel. Suspendisse cursus sagittis massa, a venenatis ante fringilla ut. Fusce elementum sit amet orci non varius. Aenean rhoncus justo tortor. Suspendisse feugiat elit massa, id tempus ante mattis et. Nunc sapien ante, commodo et orci sit amet, suscipit cursus purus. Cras ac nisi pharetra quam dictum viverra eu vel urna.

Quisque vulputate et sem ac efficitur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla luctus ullamcorper ligula id cursus. Nam velit justo, dignissim ac augue vitae, blandit dignissim nibh. Sed sit amet ultricies ante. Proin eget porta tortor. Curabitur a eros sapien. Nulla imperdiet nisl facilisis euismod sodales. Proin lobortis, risus posuere eleifend lacinia, leo enim venenatis sapien, sit amet tincidunt est lectus tempor sem. Vestibulum elementum, purus id pellentesque tristique, odio purus rhoncus lacus, non cursus dolor libero a risus. Proin non libero enim. Morbi ultricies tempor ligula. Ut sem purus, efficitur pharetra malesuada nec, molestie nec justo.

**Comment by danielspinard** [comment]
Check #1 pull request Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, turpis sit amet consectetur consectetur, neque massa vestibulum dolor, ac hendrerit risus enim et odio. Donec suscipit et erat et eleifend. Cras eu posuere turpis. Ut sed quam pulvinar, vulputate purus nec, vulputate ex. Etiam in fermentum mauris. Nullam tincidunt porta arcu. Aliquam cursus urna vel commodo eleifend.

Cras a orci at mauris gravida scelerisque. Sed feugiat, turpis viverra laoreet vehicula, sem urna euismod magna, eget ultrices velit nisi eu ipsum. Nunc maximus sem neque, non auctor dui egestas vel. Suspendisse cursus sagittis massa, a venenatis ante fringilla ut. Fusce elementum sit amet orci non varius. Aenean rhoncus justo tortor. Suspendisse feugiat elit massa, id tempus ante mattis et. Nunc sapien ante, commodo et orci sit amet, suscipit cursus purus. Cras ac nisi pharetra quam dictum viverra eu vel urna.

Quisque vulputate et sem ac efficitur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla luctus ullamcorper ligula id cursus. Nam velit justo, dignissim ac augue vitae, blandit dignissim nibh. Sed sit amet ultricies ante. Proin eget porta tortor. Curabitur a eros sapien. Nulla imperdiet nisl facilisis euismod sodales. Proin lobortis, risus posuere eleifend lacinia, leo enim venenatis sapien, sit amet tincidunt est lectus tempor sem. Vestibulum elementum, purus id pellentesque tristique, odio purus rhoncus lacus, non cursus dolor libero a risus. Proin non libero enim. Morbi ultricies tempor ligula. Ut sem purus, efficitur pharetra malesuada nec, molestie nec justo.

**Comment by zTonyzinz** [comment]
Ok👍. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse viverra quam nibh, at condimentum velit commodo fermentum. Duis suscipit nisl at orci eleifend pharetra. Vivamus sodales rhoncus ornare. Ut vel lorem nec urna tristique iaculis. Proin viverra dui id lacinia accumsan. Etiam dignissim id turpis sit amet tempus. Vivamus id mauris ante. Aliquam viverra purus vehicula, iaculis quam eu, fermentum urna. Morbi at justo mi. Duis ipsum augue, scelerisque vel est in, facilisis vestibulum augue. Integer eleifend lorem non erat facilisis hendrerit. Nulla facilisi. Praesent luctus tempor lorem, ut mollis neque tincidunt viverra. Morbi et ex sit amet nisi congue pellentesque. Nunc gravida sagittis sollicitudin. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Nam elementum pellentesque ipsum eget sodales. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In malesuada commodo sem sed congue. Morbi fringilla, ligula nec tincidunt vestibulum, mi libero gravida tortor, a laoreet metus nunc in magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam vel lorem erat. Suspendisse et volutpat mi. Fusce gravida tellus erat, eget feugiat lacus bibendum a. Duis rutrum fermentum sollicitudin. Pellentesque hendrerit tempus sapien ac molestie. Aliquam accumsan hendrerit turpis vitae auctor. Donec quam ante, posuere id fringilla a, tempor nec lacus. Etiam at ullamcorper diam, vel laoreet risus. Proin venenatis tortor ante, ut cursus nisi suscipit et. Duis at mi aliquam, porttitor sapien ac, aliquet mauris. Quisque sed mauris interdum, placerat lorem ut, consectetur mi.

**Comment by danielspinard** [comment]
Progress🚀. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse viverra quam nibh, at condimentum velit commodo fermentum. Duis suscipit nisl at orci eleifend pharetra. Vivamus sodales rhoncus ornare. Ut vel lorem nec urna tristique iaculis. Proin viverra dui id lacinia accumsan. Etiam dignissim id turpis sit amet tempus. Vivamus id mauris ante. Aliquam viverra purus vehicula, iaculis quam eu, fermentum urna. Morbi at justo mi. Duis ipsum augue, scelerisque vel est in, facilisis vestibulum augue. Integer eleifend lorem non erat facilisis hendrerit. Nulla facilisi. Praesent luctus tempor lorem, ut mollis neque tincidunt viverra. Morbi et ex sit amet nisi congue pellentesque. Nunc gravida sagittis sollicitudin. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Nam elementum pellentesque ipsum eget sodales. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In malesuada commodo sem sed congue. Morbi fringilla, ligula nec tincidunt vestibulum, mi libero gravida tortor, a laoreet metus nunc in magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam vel lorem erat. Suspendisse et volutpat mi. Fusce gravida tellus erat, eget feugiat lacus bibendum a. Duis rutrum fermentum sollicitudin. Pellentesque hendrerit tempus sapien ac molestie. Aliquam accumsan hendrerit turpis vitae auctor. Donec quam ante, posuere id fringilla a, tempor nec lacus. Etiam at ullamcorper diam, vel laoreet risus. Proin venenatis tortor ante, ut cursus nisi suscipit et. Duis at mi aliquam, porttitor sapien ac, aliquet mauris. Quisque sed mauris interdum, placerat lorem ut, consectetur mi.

**Comment by elizeujrdev** [comment]
Lol

**Comment by CauaDantas** [comment]
homeland or death. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse viverra quam nibh, at condimentum velit commodo fermentum. Duis suscipit nisl at orci eleifend pharetra. Vivamus sodales rhoncus ornare. Ut vel lorem nec urna tristique iaculis. Proin viverra dui id lacinia accumsan. Etiam dignissim id turpis sit amet tempus. Vivamus id mauris ante. Aliquam viverra purus vehicula, iaculis quam eu, fermentum urna. Morbi at justo mi. Duis ipsum augue, scelerisque vel est in, facilisis vestibulum augue. Integer eleifend lorem non erat facilisis hendrerit. Nulla facilisi. Praesent luctus tempor lorem, ut mollis neque tincidunt viverra. Morbi et ex sit amet nisi congue pellentesque. Nunc gravida sagittis sollicitudin. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Nam elementum pellentesque ipsum eget sodales. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In malesuada commodo sem sed congue. Morbi fringilla, ligula nec tincidunt vestibulum, mi libero gravida tortor, a laoreet metus nunc in magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam vel lorem erat. Suspendisse et volutpat mi. Fusce gravida tellus erat, eget feugiat lacus bibendum a. Duis rutrum fermentum sollicitudin. Pellentesque hendrerit tempus sapien ac molestie. Aliquam accumsan hendrerit turpis vitae auctor. Donec quam ante, posuere id fringilla a, tempor nec lacus. Etiam at ullamcorper diam, vel laoreet risus. Proin venenatis tortor ante, ut cursus nisi suscipit et. Duis at mi aliquam, porttitor sapien ac, aliquet mauris. Quisque sed mauris interdum, placerat lorem ut, consectetur mi.

**Comment by elizeujrdev** [comment]
my dick is so big bro. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse viverra quam nibh, at condimentum velit commodo fermentum. Duis suscipit nisl at orci eleifend pharetra. Vivamus sodales rhoncus ornare. Ut vel lorem nec urna tristique iaculis. Proin viverra dui id lacinia accumsan. Etiam dignissim id turpis sit amet tempus. Vivamus id mauris ante. Aliquam viverra purus vehicula, iaculis quam eu, fermentum urna. Morbi em apenas mi. Duis ipsum augue, scelerisque vel est in, facilisis vestibulum augue. Integer eleifend lorem non erat facilisis hendrerit. Nulla facilisi. Praesent luctus tempor lorem, ut mollis neque tincidunt viverra. Morbi et ex sit amet nisi congue pellentesque. Nunc gravida sagittis sollicitudin. Interdum et maleuada famas ac ante ipsum primis in faucibus.

Nam elementum pellentesque ipsum eget sodales. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Em malesuada comodo sem sed congue. Morbi fringilla, ligula nec tincidunt vestibulum, mi libero gravida tortor, a laoreet metus nunc in magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam vel lorem erat. Suspendisse et volutpat mi. Fusce gravida tellus erat, eget feugiat lacus bibendum a. Duis rutrum fermentum sollicitudin. Pellentesque hendrerit tempus sapien ac molestie. Aliquam accumsan hendrerit turpis vitae auctor. Donec quam ante, posuere id fringilla a, tempor nec lacus. Etiam e ullamcorper diam, vel laoreet risus. Proin venenatis tortor ante, ut cursus nisi suscipit et. Duis at mi aliquam, porttitor sapien ac, aliquet mauris. Quisque sed mauris interdum,

**Comment by zTonyzinz** [comment]
Yes, i thought about it too. But Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse viverra quam nibh, at condimentum velit commodo fermentum. Duis suscipit nisl at orci eleifend pharetra. Vivamus sodales rhoncus ornare. Ut vel lorem nec urna tristique iaculis. Proin viverra dui id lacinia accumsan. Etiam dignissim id turpis sit amet tempus. Vivamus id mauris ante. Aliquam viverra purus vehicula, iaculis quam eu, fermentum urna. Morbi at justo mi. Duis ipsum augue, scelerisque vel est in, facilisis vestibulum augue. Integer eleifend lorem non erat facilisis hendrerit. Nulla facilisi. Praesent luctus tempor lorem, ut mollis neque tincidunt viverra. Morbi et ex sit amet nisi congue pellentesque. Nunc gravida sagittis sollicitudin. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Nam elementum pellentesque ipsum eget sodales. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In malesuada commodo sem sed congue. Morbi fringilla, ligula nec tincidunt vestibulum, mi libero gravida tortor, a laoreet metus nunc in magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam vel lorem erat. Suspendisse et volutpat mi. Fusce gravida tellus erat, eget feugiat lacus bibendum a. Duis rutrum fermentum sollicitudin. Pellentesque hendrerit tempus sapien ac molestie. Aliquam accumsan hendrerit turpis vitae auctor. Donec quam ante, posuere id fringilla a, tempor nec lacus. Etiam at ullamcorper diam, vel laoreet risus. Proin venenatis tortor ante, ut cursus nisi suscipit et. Duis at mi aliquam, porttitor sapien ac, aliquet mauris. Quisque sed mauris interdum, placerat lorem ut, consectetur mi.
